---
title: "Unit 0: Testing, Testing, 1,2,3"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 1
draft: false
# search related keywords
keywords: [""]
---


::: {.callout-note}
**Canvas:** U0: Core Task 2 — Testing, Testing, 1,2,3
**Type:** Core Task (1 pt, complete/incomplete)  
**AI Use:** 🟢
:::


### Background

Each assignment will have a Background section that provides context for the project. Make sure you read the background carefully to see the big picture needs and purpose of the project.

Python and VS Code are tools commonly used in the field of data science. During our first two days of class we will primarily be installing software, libraries, extensions, etc. Completing Project 0 will set you up for success the rest of the semester. Since this project is strictly about software installation, there is no contextual background for this project.

### Data

This project will use the Palmer Penguins data set. This dataset is embedded in a library we will load, so there is no need to read it in from the link below. But in future assignments, data for the assignment can be found in this section.

__URL:__ [penguins data](https://aeturrell.github.io/python4DS/data-visualise.html#the-penguins-data-frame)   


### Readings

Please do the assigned reading **before coming to class**!

Many people have different levels of experience with Python, VS Code, and programming in general. That is why there are so many and why skimming may be a good strategy for some students, but not for others. 

- [Course Setup](../setup.qmd) (Do)
<!-- - [Learn about our Book Python for Data Science](../Course%20Materials/python.qmd) (Skim) -->
- [PY4DS: First Steps](https://aeturrell.github.io/python4DS/introduction.html) (Skim)
- [PY4DS: CH1 Whole Game](https://aeturrell.github.io/python4DS/whole-game.html) (Skim)
- [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) (Read)
- [P4DS: CH30 Markdown](https://aeturrell.github.io/python4DS/markdown.html) (Read)
- [P4DS: CH31 Quarto](https://aeturrell.github.io/python4DS/quarto.html) (Skim)
- [Quarto Instructional Template for DS](../Templates/ds250_project_template.qmd) (Read)


#### Optional References
- [Learn about VS Code](../Course%20Materials/vs_code.qmd)
- [VS Code user interface](https://code.visualstudio.com/docs/getstarted/userinterface) 
- [Reading Technical Documentation](https://byui-cse.github.io/cse450-course/course/reading-technical-documentation.html)


### Core Questions


**Skills:** Quarto + VS Code setup, HTML rendering, Polars basics

1. Download this [Project0 Template](../Templates/P0_template.qmd). The template has working code for the Penguin data set. You need to finish the project by adding code to recreate charts from the book. More specifically, copy and paste code from the book into this template quarto file to:
    1. Recreate the first table displayed at [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html)
    2. Recreate an example chart from [PY4DS: CH2 Data Visualization](https://aeturrell.github.io/python4DS/data-visualise.html) of the textbook. Specifically, the chart in from the subsection labelled "Ultimate Goal".
    3. Follow the instructions in the submission section below to submit your work

__The main purpose of this project is to ensure your set-up and installations are done correctly. You will know this is the case if you can create an html file with those graph and table in it.__

### Submission:

{{< include ../_submission_html.qmd >}}



### Deliverables:

_Use this [P0_template](../Templates/P0_template.qmd) to submit your Client Report._
 
1. _The template should include answers to the tasks. Response to each question should include a written description of your results, code cells with comments, charts and/or tables._  

::: {.callout-note collapse="false"}
_Your report should be written in quarto markdown files and rendered to an HTML File. Upload the HTML file in Canvas. (Do not submit the `.qmd` file)_  
:::
