---
title: "Unit 5 Core Task 3: Star Wars for Dummies"
date: 2025-10-29
lastmod: 2025-10-29
weight: 5
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** W12 U5: Core Task 3 — Star Wars for Dummies  
**Type:** Core Task (1 pt, complete/incomplete)  
**Copilot:** Allowed for syntax lookup; disallow for answer generation.
:::

### Background

Survey data is notoriously difficult to munge.  Even when the data is recorded cleanly the options for ‘write in questions’, ‘choose from multiple answers’, ‘pick all that are right’, and ‘multiple choice questions’ makes storing the data in a tidy format difficult.

In 2014, FiveThirtyEight surveyed over 1000 people to write the article titled, [America’s Favorite ‘Star Wars’ Movies (And Least Favorite Characters)](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/). They have provided the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/star-wars-survey). We have done some initial data cleaning and added ficitious email addresses to the dataset.

For this project, your client would like to use the Star Wars survey data in a new marketing initiative. They would like to email survey participants with product offers, but also use the responses to build a machine learning model to predict a person's outcome based on a few responses about Star Wars movies. 

Most of the data cleaning has been done for you, but there is still some data preparation that needs to take place.

### Client Request

The Client is who performed the survey but outsourced the analitics to a 3rd party (you). They want you to clean up the data so you can: 

- Extract the names of respondents and their email info
- Validate the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article
- Predict if a person from the survey makes at least $50k


### Data

__URL:__ [Star Wars data](/Data/StarWars_with_emails.csv)

__Information:__ [Article](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/)


### Readings

- [One Hot Encoding Example](https://datasensei.medium.com/how-to-transform-nominal-data-for-ml-with-onehotencoder-from-scikit-learn-f6febfefb3c6)
- [Why get_dummies is a bad idea for your ML project](https://digestize.medium.com/why-is-using-get-dummies-a-bad-idea-for-your-ml-project-bcfd2683d2e4)
- Skim Python Polars: The Definitive Guide, [Chapter 14, Vertical and Horizontal Stacking](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch14.html#id181)sections

### Core Questions


**Skills:** one-hot encoding, target creation, full ML pipeline

1. __Finish prepping the data for machine learning:__

    a. Drop the RespondentID column, first and last name columns, and email column
    a. One-hot encode all remaining non-numeric columns 
    a. Create your target (also known as “y” or “label”) column to indicate whether a person had a Household Income $50,000 or greater  

1. __Build a machine learning model that predicts whether a person had a Household Income $50,000 or greater with at least 55% accuracy. Describe your model and report the accuracy.__


### Submission / Deliverables:

__Rather than submitting something for each task of this unit, you will submit one client report at the end of the unit that is the culmination of all the tasks.__ Use [this template](../Templates/unit5_task3_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables.

{{< include ../_submission_github.qmd >}}