---
title: "Unit 2 Core Task 2: Flights - Aggregation"
date: 2025-10-29
lastmod: 2025-10-29
weight: 3
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** U2: Core Task 2 — Flights: Aggregation  
**Type:** Core Task (1 pt, complete/incomplete)  
**AI Use:** 🟡 [Class chat bot](https://gemini.google.com/gem/1yrmrFfd6yuQGpQbo6w97mj9jXFXAjx_U?usp=sharing) only allowed for code explanations and small, syntax lookup.
:::

### Background

Delayed flights are not something most people look forward to. In the best case scenario you may only wait a few extra minutes for the plane to be cleaned. However, those few minutes can stretch into hours if a mechanical issue is discovered or a storm develops. Arriving hours late may result in you missing a connecting flight, job interview, or your best friend’s wedding.

In 2003 the Bureau of Transportation Statistics (BTS) began collecting data on the causes of delayed flights. The categories they use are Air Carrier, National Aviation System, Weather, Late-Arriving Aircraft, and Security. You can visit the [BTS website](https://www.bts.gov/topics/airlines-and-airports/understanding-reporting-causes-flight-delays-and-cancellations) to read definitions of these categories.


### Client Request

The JSON file for this project contains information on delays at 7 airports over 10 years. Your task is to clean the data, search for insights about flight delays, and communicate your results to the Client. The Client is a CEO of a flight booking app who is interested in the causes of flight delays and wants to know which airports have the worst delays. They also want to know the best month to fly if you want to avoid delays of any length.


### Data
::: {.callout-note collapse="true"}
Every data science project should start with data, and our class projects are no different. Each project will have __'URL'__ and __'Information'__ links like the ones below. Right click the __'URL'__ link and select "Copy Link" to use it to import the data into your project. This is the preferred method to get data into your report as you will be publishing your report to GitHub. If you choose to download the data file to your computer you will need to save it in the same folder as your `.qmd` file for it to work correctly in GitHub. 
:::

__URL:__ [JSON File](https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json)   
__Information:__ [Data Description](https://github.com/byuidatascience/data4missing/blob/master/data.md)  
__Subject Matter:__ [Types of Delay](https://aspm.faa.gov/aspmhelp/index/Types_of_Delay.html)  


### Readings

Polars Cookbook: Chapter 4 Data Transformation Techniques

- [Exploring basic aggregation](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_04.xhtml#_idParaDest-151)
- [using group by aggregation](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_04.xhtml#_idParaDest-158)


#### Optional/alternative reading:

::: {.callout-note collapse="false"}
Polars Definitive Guide
- [Chapter 13, Summarizing and Aggregating](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch13.html) (Advanced Methods section is optional)

Polars User Guide, [Getting Started: Expressions and Context](https://docs.pola.rs/user-guide/getting-started/#expressions-and-contexts)
:::

### Core Questions


**Skills:** `group_by`, `agg`, sorting aggregates

1. __Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

1. __Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

1. __Create a barplot (polished and ready for presentation, including labels, title, etc.) showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  


### Submission / Deliverables:

_Use this [unit2_task2_template](../Templates/unit2_task2_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables._  

{{< include ../_submission_github.qmd >}}

