---
title: "Unit 5 Core Task 1: Regular Expression"
date: 2025-12-22
lastmod: 2025-12-22
weight: 5
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** U5: Core Task 1 — Regex  
**Type:** Core Task (1 pt, complete/incomplete)  
**AI Use:** 🟡 [Class chat bot](https://gemini.google.com/gem/1yrmrFfd6yuQGpQbo6w97mj9jXFXAjx_U?usp=sharing) only allowed for code explanations and small, syntax lookup.
:::

### Background

Survey data is notoriously difficult to munge.  Even when the data is recorded cleanly the options for ‘write in questions’, ‘choose from multiple answers’, ‘pick all that are right’, and ‘multiple choice questions’ makes storing the data in a tidy format difficult.

In 2014, FiveThirtyEight surveyed over 1000 people to write the article titled, [America’s Favorite ‘Star Wars’ Movies (And Least Favorite Characters)](https://byuistats.github.io/M335/star_wars_article_538.html). They have provided the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/star-wars-survey). We have done some initial data cleaning and added fictitious email addresses to the dataset.

For this project, your client would like to use the Star Wars survey data in a new marketing initiative. They would like to email survey participants with product offers, but also use the responses to build a machine learning model to predict a person's outcome based on a few responses about Star Wars movies. 

Most of the data cleaning has been done for you, but there is still some data preparation that needs to take place.

### Client Request

The Client is who performed the survey but outsourced the analitics to a 3rd party (you). They want you to clean up the data so you can: 

- Extract the names of respondents and their email info
- Validate the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article
- Predict if a person from the survey makes at least $50k


### Data

__URL:__ [Star Wars data](/Data/StarWars_with_emails.csv) 

__Information:__ [Article](https://byuistats.github.io/M335/star_wars_article_538.html)


### Readings

- [Intro to the concept of regular expression (a.k.a. regex)](http://2017.compciv.org/guide/topics/regular-expressions/regex-early-overview.html)
- Polars Cookbook, [Chapter 6, Strings](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_06.xhtml)
- [read_csv documentation](http://docs.pola.rs/api/python/stable/reference/api/polars.read_csv.html)
- [replace() documentation](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.replace_strict.html#polars.Expr.replace_strict)

#### Optional Alternative Readings

- [Video on regular expression](https://www.youtube.com/watch?v=nxjwB8up2gI)
- [Polars Users Guide: Strings](https://docs.pola.rs/user-guide/expressions/strings/#the-string-namespace)
- Python Polars: The Definitive Guide, [Chapter 12: Introduction and Strings](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch12.html#id136) sections


### Core Questions


**Skills:** regex patterns, `str.extract`, validation

1. __Load in the Star Wars Data.__ Sometimes data doesn't come in a clean format and has metadata listed before the column headers. Use the arguments in the read_csv function to avoid the rows that prevent a successful reading of the data.

2. __Remake the respondent names from the email column. Show the first 5 rows of the result.__ Each respondentID has a unique email they used to submit their survey. We can see that each of the emails have a different format for their names. 

    Use regex to create a first name column, a last name column, and a email domain column to your data set for each row. Show the first 5 rows of the result (you don't have to show all the columns, just the email, first name, last name, and email domain).

    This table should be placed either in the the Methods section or an Appendix of the report submitted for this unit (see below).

3. __Make a table that counts the number of times each domain is used.__ Note that sometimes the email domain is not lowercase. Make them uniform for clean counting.

    This table should be placed either in the the Methods section or an Appendix of the report submitted for this unit (see below).

### Submission / Deliverables:

__Rather than submitting something for each task of this unit, you will submit one client report at the end of the unit that is the culmination of all the tasks.__ Use [this template](../Templates/unit5_task3_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables.

{{< include ../_submission_github.qmd >}}

