---
title: "Unit 1 Task 1: Exploring Names"
date: 2025-03-31T11:02:05+06:00
lastmod: 2025-03-31T11:02:05+06:00
weight: 2
draft: false
# search related keywords
keywords: [""]
---

### Background

Early in prehistory, some descriptive names began to be used again and again until they formed a name pool for a particular culture. Parents would choose names from the pool of existing names rather than invent new ones for their children. 

With the rise of Christianity, certain trends in naming practices manifested. Christians were encouraged to name their children after saints and martyrs of the church. These early Christian names can be found in many cultures today, in various forms. These were spread by early missionaries throughout the Mediterranean basin and Europe.  

By the Middle Ages, the Christian influence on naming practices was pervasive. Each culture had its pool of names, which were a combination of native names and early Christian names that had been in the language long enough to be considered native. [[ref](https://heraldry.sca.org/names/namehist.html)]


### Client Request

This csv file contains the number of times a name was given to a child in a specific year. The Client has a passion for names throughout history. They would like to know how the usage of names has changed over time. They are particularly interested in the names Mary, Martha, Peter, and Paul. They would also like to know how the usage of a name from a famous movie has changed over time.


### Data

Every data science project should start with data, and our class projects are no different. Each project will have __'URL'__ and __'Information'__ links like the ones below. Right click the __'URL'__ link and select "Copy Link". You can use that copied URL in your code to read in the data. This is the preferred method to get data into your report as you will be publishing your report to GitHub. If you choose to download the data file to your computer you will need to save it in the same folder as your quarto file for the assignment in order for it to work correclty in GitHub. 


__URL:__ [names_year_csv.csv](https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv)   
__Information:__ [data.md](https://github.com/byuidatascience/data4names/blob/master/data.md)


### Readings

::: {.callout-note collapse="true"}
Complete these readings before we cover the material in class. This will help you retain the material and make the class period more engaging - not less. 

In other words, if an assignment is due on Wednesday, we will cover the material needed to complete the assignment on Tuesday. Therefore, you should complete the readings on Monday (or anytime before class on Tuesday).
:::

Read the Polars Cookbook, Chapter 1: Getting Started with Python Polars to get some fundamental understanding of polars and data structures in python. Specifically, read the following sections of the chapter (you can skip the other sections):

- [Introducing Key Features in Polars](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_01.xhtml#_idParaDest-23)
- [The Polars DataFrame](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_01.xhtml#_idParaDest-29)
- [The Polars Series](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_01.xhtml#_idParaDest-36)
- [Understanding Method Chaining](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_01.xhtml#_idParaDest-59)

For working with rows and columns of a data frame in polars, read the following sections of Python Polars: The Definitive Guide:

- Chapter 7 - Beginning Expressions: [Selecting Columns with Expressions](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch07.html#id287) section
- [Chapter 11 - Filtering and Sorting Rows](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch11.html). (You can skip the "Sort Nested Data Types" section if you wish)

Optional:

The [Selecting Columns and Filtering Data](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_01.xhtml#_idParaDest-47) section of Chapter 1 in the Polars Cookbook.

### Questions and Tasks (Core)

__Download this [Unit 1 Task 1](../Templates/unit1_task1_template.qmd) template. The answer to each question should include code and an answer written in a full sentence.__  

1. __What was the earliest year that the name ‘Felisha’ was used?__  
1. __What year had the most babies named 'David'? How many babies were named 'David' that year?__  
1. __What year did your name hit its peak? How many babies were named your name in that year?__
1. __How many babies are named ‘Oliver’ in the state of Utah for all years?__
1. __In the most recent year of data, what was the most common female name in Utah?__   

### Submission:
::: {.callout-note collapse="false"}
When you have completed the report, you will need to follow this process to submit your work:

1. Have this assignment's template/quarto file open in VS Code and nothing else
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the file but also the entire course work portfolio into `HTML` files for review
    b. Confirm everything displays as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open a VS Code `Terminal`
    a. click `Terminal` in the top menu bar and then `New Terminal`
1. Type the following in the terminal `quarto render `
    a. Then drag and drop `unit1_task1.qmd` into the terminal, this will add the file path to the terminal command
    a. Press Enter
1. This will render the project into a `HTML` file in the same location as the `.qmd` file
1. To locate the file in VS Code
    a. Right click on the file in the file explorer and select `Reveal in File Explorer`(Win) or `Reveal in Finder`(Mac)
1. Upload `HTML` file into Canvas
:::


### Deliverables:

::: {.callout-note collapse="true"}
Deliverables are “the quantifiable goods or services that must be provided upon the completion of a project”. In this class the deliverable for each project is a .html file report created using Quarto files. This final section will be the same for each project. 
:::

_Use this [Unit1_Task1 template](../Templates/unit1_task1_template.qmd) to submit your Client Report._
 
1. _Answers to the questions | tasks. Each should include a written description of your results, code cells with comments, and any charts and/or tables._  

::: {.callout-note collapse="false"}
_Your report should be written in quarto markdown files and rendered to an HTML File. Upload the HTML file in Canvas. (Do not submit the `.qmd` file)_  
:::
