---
title: "Unit 4 Core Task 1: Can You Predict That?"
date: 2025-10-29
lastmod: 2025-10-29
weight: 5
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** U4: Core Task 1 — Can You Predict That?  
**Type:** Core Task (1 pt, complete/incomplete)  
**AI Use:** 🟡 [Class chat bot](https://gemini.google.com/gem/1yrmrFfd6yuQGpQbo6w97mj9jXFXAjx_U?usp=sharing) only allowed for code explanations and small, syntax lookup.
:::


### Background

The clean air act of 1970 was the beginning of the end for the use of asbestos in home building.  By 1976, the U.S. Environmental Protection Agency (EPA) was given authority to restrict the use of asbestos in paint. Homes built during and before this period are known to have materials with asbestos You can [read more about this ban](https://www.asbestos.com/mesothelioma-lawyer/legislation/ban/).  

The state of Colorado has a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can __classify__ if a house is built pre 1980.  

Colorado gave you home sales data for the city of Denver from 2013 on which to train your model. They said all the column names should be descriptive enough for your modeling and that they would like you to use the latest machine learning methods.


### Client Request

The Client is a state agency in Colorado that is responsible for the health and safety of its residents. They have a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can classify if a house is built pre 1980.


### Data

__URL:__  [dwellings_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv)  
__Optional URL:__  [dwellings_neighborhoods_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_neighborhoods_ml/dwellings_neighborhoods_ml.csv)  
__Informational URL:__  [dwellings_denver.csv (not cleansed)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_denver/dwellings_denver.csv)  
__Information:__ [Data description](https://github.com/byuidatascience/data4dwellings/blob/master/data.md)  


### Readings

- [Machine Learning Introduction](/Course%20Materials/ml.qmd)
- [A visual introduction to machine learning](https://narrative-flow.github.io/exploratory-study-2/)
- [Calculate model accuracy in scikit-Learn](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html)
- [A few popular models to choose from, and a review of Machine Learning workflow](https://www.educative.io/blog/scikit-learn-cheat-sheet-classification-regression-methods)
- [Exhaustive list of classifiers in scikit-Learn](https://www.kaggle.com/code/grigol1/all-classification-models-40-sklearn-models) (skim)


#### Optional References

- [Decision Tree Classification in Python](https://www.datacamp.com/community/tutorials/decision-tree-classification-python)    
- [Boosted algorithms in scikit-learn](https://scikit-learn.org/stable/modules/ensemble.html#gradient-tree-boosting)
- [scikit-plot package](https://github.com/reiinakano/scikit-plot)  
 

### Core Questions


**Skills:** scikit-learn, train/test split, first classifier

1. __Take time to get to know your data.__ Based on some initial exploration, identify 3 variables in the dataset you think will have strong predictive ability for determining if a house was built before 1980. Explain/justify the reasoning behind your guesses (for example with plots).


1. __Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to get 91% accuracy, or higher. Report your final model choice and any other model parameters you may have tweaked (train-test split ratio, tuning parameters, etc).  

### Submission / Deliverables:

_Use this [unit4_task1_template](../Templates/unit4_task1_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables._  

{{< include ../_submission_github.qmd >}}
