---
title: "Project 5: Can you validate me?"
date: 2025-10-29
lastmod: 2025-10-29
weight: 5
draft: false
# search related keywords
keywords: [""]
---

### Background

Survey data is notoriously difficult to munge.  Even when the data is recorded cleanly the options for ‘write in questions’, ‘choose from multiple answers’, ‘pick all that are right’, and ‘multiple choice questions’ makes storing the data in a tidy format difficult.

In 2014, FiveThirtyEight surveyed over 1000 people to write the article titled, [America’s Favorite ‘Star Wars’ Movies (And Least Favorite Characters)](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/). They have provided the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/star-wars-survey). We have done some initial cleaning and added ficitious email addresses to the dataset.

For this project, your client would like to use the Star Wars survey data in a new marketing initiative. They would like to email survey participants with product offers, but also use the responses to build a machine learning model to predict a person's outcome based on a few responses about Star Wars movies. 

Most of the data cleaning has been done for you, but there is still some data preparation that needs to take place.

### Client Request

The Client is who performed the survey but outsourced the analitics to a 3rd party (you). They want you to clean up the data so you can: 
    a. Extract the names of respondents and their email info
    a. Validate the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article
    a. Predict if a person from the survey makes at least $50k


### Data

__URL:__ [Star Wars data]({{<site-path>}}/Data/StarWars_with_emails.csv)

__Information:__ [Article](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/)


### Readings

This is a chance to use skills learned in this unit and practice skills learned in previous units. 

Review pivoting and unpivoting.

-Python Polars: The Definitive Guide, [Chapter 15 Reshaping (especially pivoting and unpivoting)](https://learning.oreilly.com/library/view/python-polars-the/9781098156077/ch15.html)

#### Optional Alternative Reading

Polars Cookbook, [Chapter 8 Reshaping and Tidying Data](https://learning.oreilly.com/library/view/polars-cookbook/9781805121152/B21621_08.xhtml#_idParaDest-270)

### Questions

1. __Validate that the data provided lines up with the article by recreating 2 of the visuals from the article.__ These visuals should be similar, including titles, subtitles, gridlines, order of categories, colors, etc. But, they don’t have to be exact. They need to be close enough that we can validate that the values in the dataset match the graphs in the chart. Though their charts were built using a different plotting software, the more you push yourself for an exact replica, the more you will learn. Spend at least a couple of hours on this.


### Submission / Deliverables:

__Rather than submitting something for each task of this unit, you will submit one client report at the end of the unit that is the culmination of all the tasks.__ Use [this template](../Templates/unit5_task3_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables. xn 

::: {.callout-note collapse="true"}
Your instructor will advise you, or it will be evident in Canvas, whether to submit an rendered .html file, or a link to the rendered file on GitHub on gh-pages. (Do not submit the URL to the GitHub `.qmd` file)  
:::

Here are some reminder instructions if you are using GitHub:

::: {.callout-note collapse="true"}
When you have completed the report and are ready to submit it, you will need to render the project into HTML files and publish it to GitHub pages. Follow these steps:

1. Have this assignment's template/quarto file open in VS Code and nothing else
1. Click `Preview Button` in VS Code in the top right of the screen
    a. This will render the project but also entire course work portfolio into `HTML` files for review
    b. Confirm everything displas as you would like it to
    c. How you see it will be how it is viewed for grading
    d. If there is an error in any cell of the quarto files, the rendering will stop and you will need to fix the error before rendering again (if you get stuck post your error in Slack)
1. Once the report is confirmed close the preview and open the `GitHub Desktop` application
1. Confirm you are in the correct repository in the top left corner of the screen
1. Confirm you are on the correct branch `Main` in the top left corner of the screen (Never change off the `Main` branch)
1. Type a summary of the changes in the `Summary` box
1. Click `Commit to main` blue button in the bottom left corner
1. Click `Push origin` blue button in the middle right of the screen
    a. This will push all your changes in the project .qmd file to GitHub
    b. The publish.yml file will kick off an automated process to render the project into HTML files
    c. The HTML files will be published to GitHub pages in the gh-pages branch
    d. The URL to the published project will be in the deployment section in GitHub
        1. In `GitHub Desktop` click `Open in GitHub` to navigete to the repository
        2. Click on the `Actions` tab and make sure there were no errors in the rendering process
        3. Click on the `deployment` section of the main page of the repository to find the URL
        4. Navigate to the URL and confirm it displays as you intended
        5. Copy the URL and submit it in Canvas
:::