---
title: "Unit 5 Core Task 2: Recoding Range Variables"
date: 2025-10-29
lastmod: 2025-10-29
weight: 5
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** U5: Core Task 2 — Recoding Variables for ML  
**Type:** Core Task (1 pt, complete/incomplete)  
**Copilot:** Allowed for syntax lookup; disallow for answer generation.
:::

### Background

Survey data is notoriously difficult to munge.  Even when the data is recorded cleanly the options for ‘write in questions’, ‘choose from multiple answers’, ‘pick all that are right’, and ‘multiple choice questions’ makes storing the data in a tidy format difficult.

In 2014, FiveThirtyEight surveyed over 1000 people to write the article titled, [America’s Favorite ‘Star Wars’ Movies (And Least Favorite Characters)](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/). They have provided the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/star-wars-survey). We have done some initial data cleaning and added ficitious email addresses to the dataset.

For this project, your client would like to use the Star Wars survey data in a new marketing initiative. They would like to email survey participants with product offers, but also use the responses to build a machine learning model to predict a person's outcome based on a few responses about Star Wars movies. 

Most of the data cleaning has been done for you, but there is still some data preparation that needs to take place.

### Client Request

The Client is who performed the survey but outsourced the analitics to a 3rd party (you). They want you to clean up the data so you can: 

- Extract the names of respondents and their email info
- Validate the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article
- Predict if a person from the survey makes at least $50k


### Data

__URL:__ [Star Wars data](/Data/StarWars_with_emails.csv)   

__Information:__ [Article](https://fivethirtyeight.com/features/americas-favorite-star-wars-movies-and-least-favorite-characters/)


### Readings

No new readings. Apply the new concepts in this unit and review/practice concepts from past units.


### Core Questions


**Skills:** ordinal encoding, recoding ranges to numbers

1. __Filter the dataset to 835 respondents that have seen at least one film__ (Hint: Don’t use the column `Have you seen any of the 6 films in the Star Wars franchise?`)

1. __*Begin* to clean and format the data so that it can be used in a machine learning model.__ As you format the data, you should complete each item listed below. In your final report provide an excerpt of the reformatted data with a short description of the changes made.  

    a. Create a new column that converts the age ranges to a number. Remove the original age range categorical column  
    a. Create a new column that converts the education groupings to a number. Remove the original school categorical column  
    a. Create a new column that converts the income ranges to a number. Remove the original income range categorical column  
    a. Create a new column that converts favorability ratings to a number. Remove the original favorability categorical columns.


### Submission / Deliverables:

__Rather than submitting something for each task of this unit, you will submit one client report at the end of the unit that is the culmination of all the tasks.__ Use [this template](../Templates/unit5_task3_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables.

{{< include ../_submission_github.qmd >}}