---
title: "Unit 4 Core Task 3: Show me"
date: 2025-10-29
lastmod: 2025-10-29
weight: 5
draft: false
# search related keywords
keywords: [""]
---

::: {.callout-note}
**Canvas:** W10 U4: Core Task 3 — Show Me  
**Type:** Core Task (1 pt, complete/incomplete)  
**Copilot:** Allowed for syntax lookup; disallow for answer generation.
:::


### Background

The clean air act of 1970 was the beginning of the end for the use of asbestos in home building.  By 1976, the U.S. Environmental Protection Agency (EPA) was given authority to restrict the use of asbestos in paint. Homes built during and before this period are known to have materials with asbestos You can [read more about this ban](https://www.asbestos.com/mesothelioma-lawyer/legislation/ban/).  

The state of Colorado has a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can __classify__ if a house is built pre 1980.  

Colorado gave you home sales data for the city of Denver from 2013 on which to train your model. They said all the column names should be descriptive enough for your modeling and that they would like you to use the latest machine learning methods.


### Client Request

The Client is a state agency in Colorado that is responsible for the health and safety of its residents. They have a large portion of their residential dwelling data that is missing the year built and they would like you to build a predictive model that can classify if a house is built pre 1980.


### Data

__URL:__  [dwellings_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv)  
__Optional URL:__  [dwellings_neighborhoods_ml.csv (ml ready)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_neighborhoods_ml/dwellings_neighborhoods_ml.csv)  
__Informational URL:__  [dwellings_denver.csv (not cleansed)](https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_denver/dwellings_denver.csv)  
__Information:__ [Data description](https://github.com/byuidatascience/data4dwellings/blob/master/data.md)  


### Readings

A scan of these articles can be helpful, or find your own resources on the web.

- [Exhaustive list of classifiers in scikit-Learn](https://www.kaggle.com/code/grigol1/all-classification-models-40-sklearn-models) (skim)
- [Pros and cons of popular classifiers](https://www.geeksforgeeks.org/comprehensive-guide-to-classification-models-in-scikit-learn/) 
- [Another overview and description of pros and cons for popular classifiers and regression models](https://www.geeksforgeeks.org/supervised-machine-learning/)
- [Decision Tree Classification in Python](https://www.datacamp.com/community/tutorials/decision-tree-classification-python)    
- [Boosted algorithms in scikit-learn](https://scikit-learn.org/stable/modules/ensemble.html#gradient-tree-boosting)
- [scikit-plot package](https://github.com/reiinakano/scikit-plot) 
 

### Core Questions


**Skills:** model comparison, permutation importance

1. __Repeat the classification exercise using 2 different algorithms/models. Explain the differences between the 3 models__ (your original one, and the 2 new ones for this task).

1. For each model (your original one, and the 2 new ones for this task), display the classification report and the permutation importances for the most important features.  Discuss which model you would recommend to the client and why.



### Submission / Deliverables:

_Use this [unit4_task3_template](../Templates/unit4_task3_template.qmd) to create your Client Report. Answer the questions. Each answer should include a written description of your results, code cells with comments, charts and/or tables._  

{{< include ../_submission_github.qmd >}}