---
title: "Client Report - Missing Data and JSON"
subtitle: "Unit 3 Task 1"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests
import io
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```



```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# I guess the read_json function is a little picky and it likes having the files be a local path. We can use the io package to essentially do the same thing a tempfile does in 350

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

## QUESTION 1

1. __Create a new 'season' column.__ Define 'season' as:
    1. Winter for January, Febuary (note the mispelling), March
    1. Spring for April, May, June
    1. Summer for  July, August, September
    1. Fall for October, November, December
    1. All other rows can be assigned a value of 'Unknown' 

_Describe your results and analysis here_

```{python}
# Include and execute your code here
q1 = df.with_columns([
    pl.when(pl.col('month').is_in(['January', 'Febuary', 'March']))
    .then(pl.lit('Winter'))
    .when(pl.col('month').is_in(['April', 'May', 'June']))
    .then(pl.lit('Spring'))
    .when(pl.col('month').is_in(['July', 'August', 'September']))
    .then(pl.lit('Summer'))
    .when(pl.col('month').is_in(['October', 'November', 'December']))
    .then(pl.lit('Fall'))
    .otherwise(pl.lit('Unknown')).alias('season')
])

```

## QUESTION 2

1. __Divide all the columns by 1000 whose name starts with num_of.__ Be sure to first filter out rows that contain problematic values for the columns like -999 or 1500+.

_Describe your results and analysis here_

```{python}
# Remove the -999 and 1500+, and convert num_of_delays_carrier to integer.
# They will have to discover the integer thing on their own, but their CSE110 coding class should have prepared them to do that or know about that kind of thing.

q2= ( q1.filter(pl.col('num_of_delays_carrier') != "1500+",
                pl.col('num_of_delays_late_aircraft') != -999)
        .with_columns(pl.col('num_of_delays_carrier').cast(int))
)

```

There are 3 ways to do the division. It would be fun for them to learn about expression expansion.

### way 1 Brute force, list each column separately
```{python}
q3 = q2.with_columns((pl.col('num_of_flights_total',
                        'num_of_delays_carrier',
                        'num_of_delays_late_aircraft',
                        'num_of_delays_nas',
                        'num_of_delays_security',
                        'num_of_delays_weather',
                        'num_of_delays_total') / 1000) )
```

### way 2 short way with regex

Students haven't learned regex, but they might know it from a different class or will have seen a little bit in the reading.

```{python}
q3= q2.with_columns(
    (pl.col("^num_of_.*$") / 1000)
)
```

### way 3 short way with polars selectors

Students haven't learned column selectors yet, but they will have seen a them in the reading.

```{python}
import polars.selectors as cs

q3 = q2.with_columns(
    (cs.starts_with("num_of") / 1000)
)
```


## QUESTION 3

1. According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “NAS” and “Late-Arriving Aircraft” categories. __Using the columns you modified in the bullet above, your job is to create a new column that calculates the total number of flights (in 1,000's) delayed by weather (both severe and mild).__ Show your work by printing the first 5 rows of the dataset. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the Late-Arriving category are due to weather  
    a. From April to August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%  

_No discussion needed for this question_

```{python}
# Include and execute your code here
q4 = q3.with_columns(
    (     pl.col('num_of_delays_late_aircraft') * 0.3 
        + pl.col('num_of_delays_weather')
        + pl.when(pl.col('month').is_in(['April', 'May', 'June', 'July', 'August']))
            .then(pl.col('num_of_delays_nas')*.4)
            .otherwise(pl.col('num_of_delays_nas')*.65)
    )
    .alias('new_weather')
)

```

## QUESTION 4

1. __Using the new weather variable calculated above, create a boxplot showing the distribution of flights delayed by weather for each season. Describe what you learn from this graph.__    

_Describe your results and analysis here_

```{python}
# Include and execute your code here
ggplot(data = q4, mapping = aes(x = 'season', y = 'new_weather')) + geom_boxplot() + labs(title = "Weather delays in a month", y = "# of flights delayed") + theme(axis_title_x= element_blank())

```