


```{python}
import polars as pl
import numpy as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

Try reading in the starwars data. Explain why it doesn't work. HINT: Look at the csv. 


```{python}
# data = pl.read_csv('starwars_skip_rows10.csv')
```

Now read it in correctly

```{python}
# data = pl.read_csv('starwars_skip_rows10.csv',
# skip_rows=10)
data = pl.read_csv('starwars_skip_rows102.csv',
skip_rows=10)
data.head()
data.shape
```

Each respondentID has a unique email they used to submit their survey. We can see that each of the emails have a different format for their names. 

Use regex to create a first and last name column for each email.
- Make a table that 


```{python}
data = data.with_columns([
    pl.when(pl.col("email").str.to_lowercase().str.contains("gmail"))
      .then(pl.lit(1))
    .when(pl.col("email").str.to_lowercase().str.contains("yahoo"))
      .then(pl.lit(2))
    .when(pl.col("email").str.to_lowercase().str.contains("myorg"))
      .then(pl.lit(3))
    .otherwise(pl.lit(4))
    .alias("email_type")
])

data.select(["email", "email_type"]).head(10)
```

- Make a table that counts the number of times each domain is used

```{python}
data.group_by('email_type').agg(
    pl.col('email_type').count().alias('domail_count')
)
```

- grab the first and last names from gmail and yahoo

```{python}
data = data.with_columns([
    # everything before the first @
    pl.col("email").str.replace(r"@.*$", "", literal=False).alias("name"),

    # everything after the last @
    pl.col("email").str.replace(r"^.*@", "", literal=False).alias("domain"),
])



data.head()
```


you have to str.to_lower and str.strip >:)

```{python}

data = data.with_columns([
    pl.col('domain').str.strip_chars_end().str.to_lowercase().alias('domain')
])


# data = data.with_columns([
#     pl.when(pl.col('domain').str.to_lowercase() == 'gmail')
#     .then(pl.col('name').str.replace(r"\..*$", ""))
#     .when(pl.col('domain').str.to_lowercase() == 'yahoo')
#     .then(pl.col('name').str.replace(r"^.*_", ""))
#     .otherwise(pl.lit('aaa'))
#     .alias('first_name')
# ])

# Make first name
data = data.with_columns([
    pl.when(pl.col('domain') == 'gmail')
    .then(pl.col('name').str.replace(r"\..*$", ""))
    .when(pl.col('domain') == 'yahoo')
    .then(pl.col('name').str.replace(r"^.*_", ""))
    .otherwise(pl.col('name').str.extract(r"\d+(.*)$", 1))
    .alias('first_name')
])

# Make last name
data = data.with_columns([
    pl.when(pl.col('domain') == 'gmail')
    .then(pl.col('name').str.replace(r"^.*\.", ""))
    .when(pl.col('domain') == 'yahoo')
    .then(pl.col('name').str.replace(r"_.*$", ""))
    .otherwise(pl.col('name').str.replace(r'\d.*$', ""))
    .alias('last_name')
])


data.select('name','first_name', 'last_name', 'domain').head(5)
```

try to join the names.csv onto our table using first and last name columns 


```{python}
# names = pl.read_csv('names.csv')
# names.head()

# names = names.with_columns(
#     pl.col("first_name").str.to_lowercase().alias("first_name_lower")
# )

# joined = (
#     names.join(data, how="cross")
#     .filter(
#         pl.col("first_name_lower").str.starts_with(
#             pl.col("first_name2")
#         )
#         &
#         pl.col("last_name").str.to_lowercase().str.starts_with(
#             pl.col("last_name2")
#         )
#     )
# )

# cleaned = joined.drop([
#     "domain",
#     "name",
#     "first_name_lower",
#     "email_type",
#     "unique_num",
#     "email_right",
#     "email_type_right",
#     "first_name2",
#     "last_name2"
# ])

# cleaned.shape
# cleaned.head(10)
```

There seems to be a bug with joining the second table. I thought polars would allow more nuanced joining, but no dice. It may be easier to change myorg to be the full name but keep the numbers in it. Then maybe I should add a fourth annoying gmail structure that they need to dance around with regex replace.