```{python}
import polars as pl
import requests
import io
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# I guess the read_json function is a little picky and it likes having the files be a local path. We can use the io package to essentially do the same thing a tempfile does in 350

url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```

At this point the students don't know how to clean the data so we need to avoid anything that would clean it.

Ideas:


```{python}
df.describe()
```


## Idea 1

We can try to use the same question about finding the true weather delays, the only issue is that they don't know how to clean the data yet and num_late_aircraft has missing values in the form of -999. We can either choose a different column or just ignore it for now with a clever use of otherwise.

The code is in section 2

## Idea 2

I think it would be a good idea to ahve them make a boxplot for this assignemnt. We can have them do it based off months, or by seasons fairly easily.

I have two ideas, we can either have them make a new column with the when().then().otherwise() logic and then plot that in their boxplots, or we can make seasons. Or we can do both so they have to use the conditional statements twice in one question.

We need to include something in the reading about pl.lit and how it means we want to use a string and we are not referring to a column.

Another idea for this assignment is that instead of having them fill the na values, they have to use filter to avoid them and they realize how annoying inconsistent na values can be >:). 
```{python}
q2 = df.filter(pl.col('month') !=  'n/a').with_columns([
    pl.when(pl.col('month').is_in(['January', 'Febuary', 'March']))
    .then(pl.lit('Winter'))
    .when(pl.col('month').is_in(['April', 'May', 'June']))
    .then(pl.lit('Spring'))
    .when(pl.col('month').is_in(['July', 'August', 'September']))
    .then(pl.lit('Summer'))
    .when(pl.col('month').is_in(['October', 'November', 'December']))
    .then(pl.lit('Fall'))
    .otherwise(pl.lit('Unknown')).alias('season')
])


q2 = q2.filter(pl.col('num_of_delays_late_aircraft') != -999).with_columns([
    ( pl.col('num_of_delays_late_aircraft')*.3 
        +pl.col('num_of_delays_weather')
        +pl.when(pl.col('month').is_in(['April', 'May', 'June', 'July', 'August'])).then(pl.col('num_of_delays_nas')*.4).otherwise(pl.col('num_of_delays_nas')*.65))
    .alias('new_weather')
])
```

```{python}

q2.group_by('month').count().to_pandas()
# q2.group_by('season').count().to_pandas()

```

```{python}
plot = (
    ggplot(q2, aes(x='month', y='new_weather'))
    +geom_boxplot()
)

plot
```

```{python}
plot = (
    ggplot(q2, aes(x='season', y='num_of_delays_weather'))
    +geom_boxplot()
)

plot
```

```{python}
plot = (
    ggplot(q2, aes(x='season', y='new_weather'))
    +geom_boxplot()
)

plot
```

I think this is enough for when.then.otherwise and they should get the idea.

## Expression Expansion Idea

### Idea 1
Many of the columns contain minutes delayed for a particular reason, or the total minutes delayed. Use expression expansion to convert all the columns from minutes to hours by dividing their values by 60. 

The problem with all these solutions is that the column still says "minutes". 
```{python}
#long way
q3 = q2.with_columns((pl.col('minutes_delayed_carrier',
                       'minutes_delayed_late_aircraft',
                        'minutes_delayed_nas',
                        'minutes_delayed_security',
                        'minutes_delayed_weather',
                        'minutes_delayed_total') / 60).round(2) )
q3
```

```{python}
#short way with regex
q2.select(
    (pl.col("^minutes_.*$") / 60).round(2)
)

```


```{python}
#short way with polars selectors
import polars.selectors as cs

q2.select(
    (cs.starts_with("minutes") / 60).round(2)
)
```


```{python}
#fix the column name problem of minutes to hours
# this seems a bit too complicated
import polars.selectors as cs

q2.with_columns([
    (pl.col(col) / 60).alias(col.replace("minutes", "hours"))
    for col in q2.select(cs.starts_with("minutes")).columns  
]
)
```

### Idea 2

Maybe just convert all the num_of_delays columns to be in hundreds (i.e. divide them all by 100). __NOTE: If we did this idea, I think we should do this before calculating the new "weather delays" column.__

But the num_of_delays_carrier is a string, so we have to convert it first. Is that too much too soon? (I don't think so, since they do casting in CSE110 a few times). Maybe we would have to give them a hint, but I think having them figure it out on their own is a good idea, if we cover a similar issue in class. For the online section though a hint may be necessary.

 I guess we could have them just convert the column 3 columns that will be used for future calculations, but that misses the opportunity to show them these other short cuts for selecting multiple columns.

Any other ideas??!

```{python}
#long way
q3= q2.filter(pl.col('num_of_delays_carrier') != "1500+").with_columns(pl.col('num_of_delays_carrier').cast(int))

q3.with_columns((pl.col('num_of_delays_carrier',
                       'minutes_delayed_late_aircraft',
                        'minutes_delayed_nas',
                        'minutes_delayed_security',
                        'minutes_delayed_weather',
                        'minutes_delayed_total') / 100) )


#short way with regex
q3.select(
    (pl.col("^num_of_delays_.*$") / 100)
)

#short way with polars selectors
import polars.selectors as cs

q3.select(
    (cs.starts_with("num_of_delays") / 100)
)
# ```