---
title: "Unit 1 Task 3: Famous Names"
date: 2025-03-31
lastmod: 2025-03-31
weight: 2
draft: false
# search related keywords
keywords: [""]
---

### Background

Early in prehistory, some descriptive names began to be used again and again until they formed a name pool for a particular culture. Parents would choose names from the pool of existing names rather than invent new ones for their children. 

With the rise of Christianity, certain trends in naming practices manifested. Christians were encouraged to name their children after saints and martyrs of the church. These early Christian names can be found in many cultures today, in various forms. These were spread by early missionaries throughout the Mediterranean basin and Europe.  

By the Middle Ages, the Christian influence on naming practices was pervasive. Each culture had its pool of names, which were a combination of native names and early Christian names that had been in the language long enough to be considered native. [[ref](https://heraldry.sca.org/names/namehist.html)]


### Client Request

This csv file contains the number of times a name was given to a child in a specific year. The Client has a passion for names throughout history. They would like to know how the usage of names has changed over time. They are particularly interested in the names Mary, Martha, Peter, and Paul. They would also like to know how the usage of a name from a famous movie has changed over time.


### Data

Every data science project should start with data, and our class projects are no different. Each project will have __'URL'__ and __'Information'__ links like the ones below. Right click the __'URL'__ link and select "Copy Link". You can use that copied URL in your code to read in the data. This is the preferred method to get data into your report as you will be publishing your report to GitHub. If you choose to download the data file to your computer you will need to save it in the same folder as your quarto file for the assignment in order for it to work correclty in GitHub.  


__URL:__ [names_year_csv.csv](https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv)   
__Information:__ [data.md](https://github.com/byuidatascience/data4names/blob/master/data.md)


### Readings

No new readings. Review the readings in the previous tasks as needed. Consider reading the optional readings in those sections if you have not yet.

### Questions and Tasks

__Download this [Unit 1 Task 3 Template](../Templates/unit1_task3_template.qmd) template. The answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **one** of your charts must include reference marks.__    

1. __Select only the column states that you have lived in, then make a new column that represents the total across those states in which you have lived. (If you have only ever lived in one state, pick at least one other state so you get practice summing across columns). Make a graph displaying that total for your name over time.__  
1. __For each year, calculate what proportion of the total babies with your came from Idaho or Utah? Make a graph displaying the proportion over time.__
1. __Calculate the total number of babies named *** by summing the values across the 50 individual state columns. For each year, compare your calculated total to the number in the 'Total' column. Create a graph to show what you discovered? Discuss/speculate why you think that might be the case.__