---
title: "Course Setup"
---

### How to get your computer setup?

The left navigation bar is sequenced for the setup process:  

This course uses Slack as our main tool for communication and collaboration.  You will need to install Slack on your laptop and mobile device.  You will also need to create a Slack account using your BYU-Idaho email. If you have an existing account, you can either change your email to the BYU-Idaho email or you can create a new account.

2. Install Slack on your laptop: 
    * [Windows](https://slack.com/downloads/windows)  
    * [Mac](https://slack.com/intl/en-in/downloads/mac)  
3. Install Slack on your Cell: 
    * [Android](https://slack.com/downloads/android)  
    * [iPhone](https://slack.com/downloads/ios)
4. Create a Slack Account using your BYU-Idaho email (abcd######@byui.edu): 
    * [Slack](https://slack.com/get-started#/createnew) 
    * Note: if you use your username@byui.edu instead of your BYU-Idaho email, this will cause issues when the instructor uses your email from canvas it will not directly add you to the class channel.

To install Python and VS code on your own laptop, start here:  

5. Install [Python](/Setup/python_setup.qmd)
6. Install [Python Libraries](/Setup/python_lib.qmd)    
7. Install [VS Code](/Setup/vs_code_setup.qmd)  
8. Install [Quarto](/Setup/quarto_setup.qmd)  

You will need to use SQL in Week 6:

9. [SQL](/Setup/sql_setup.qmd) setup and test

You will need to use GitHub from Week 8 on:

10. Install [Git & GitHub](/Setup/git_github_setup.qmd)

Using Copilot (AI)?

>Copilot is a micro-assistant that helps you write better code. It is a VS Code extension that uses AI built off Chat GPT. With your student GitHub account, you can use Copilot for free. It helps you write code faster and with fewer errors. It is not perfect, but it is a great tool to help you learn to code.

>This course is designed with a Core and Stretch for each project. It is expected that you accomplish the Core __**without**__ the use of Copilot. The Stretch is where you __**should**__ use Copilot. Without using Copilot, the stretch questions will be more challenging. The goal is to help you learn to code and to use Copilot as a tool to help you learn, not to do the work for you.

11. Install [GitHub Copilot](/Setup/copilot_setup.qmd) (required for Stretch Questions)

Prefer an Open Source AI tool try [Llama](https://ollama.com/library/codellama)?  

>Llama is an AI-powered code editor that helps you write better code. It is a VS Code extension that uses AI built off Chat GPT-4. With your student GitHub account, you can use Llama for free. It helps you write code faster and with fewer errors. It is not perfect either, but it is a great tool to help you learn to code.

12. Install [Llama](https://generativeai.pub/100-local-llama-coding-assistant-bye-bye-gpt-4-cbd2b507b822) (optional)

If you have continual problems with the setup above a AWS Cloud Virtual Machine (VM) might be a better option instead of your laptop and install Python and VS Code on that VM, start here:  

13. Create an [AWS EC2 VM](/Setup/aws_setup.qmd) (optional - recomended only if you have hardware or operating system issues with the setup above)  