---
title: "Git and GitHub for DS"
date: 2020-05-01T11:02:05+06:00
lastmod: 2020-09-15T10:42:26+06:00
weight: 8
draft: false
# search related keywords
keywords: [""]
---

Note: Changes have been made to this course since the video was recorded. The video is still relevant and will be updated in the future to reflect the changes. For conflicts of the video and the text, the text is the most current.

```{=html}
<iframe id="kaltura_player" src="https://cdnapisec.kaltura.com/p/1157612/sp/115761200/embedIframeJs/uiconf_id/41338032/partner_id/1157612?iframeembed=true&playerId=kaltura_player&entry_id=1_oqjilp7j&flashvars[localizationCode]=en&amp;flashvars[sideBarContainer.plugin]=true&amp;flashvars[sideBarContainer.position]=left&amp;flashvars[sideBarContainer.clickToClose]=true&amp;flashvars[chapters.plugin]=true&amp;flashvars[chapters.layout]=vertical&amp;flashvars[chapters.thumbnailRotator]=false&amp;flashvars[streamSelector.plugin]=true&amp;flashvars[EmbedPlayer.SpinnerTarget]=videoHolder&amp;flashvars[dualScreen.plugin]=true&amp;flashvars[Kaltura.addCrossoriginToIframe]=true&amp;&wid=1_vsr13bv6" width="608" height="402" allowfullscreen webkitallowfullscreen mozAllowFullScreen allow="autoplay *; fullscreen *; encrypted-media *" sandbox="allow-downloads allow-forms allow-same-origin allow-scripts allow-top-navigation allow-pointer-lock allow-popups allow-modals allow-orientation-lock allow-popups-to-escape-sandbox allow-presentation allow-top-navigation-by-user-activation" frameborder="0" title="W0 - Setup Git and GitHub"></iframe>
```  

### Setup Git and GitHub 
#### GitHub will be used for publishing all projects

1. Install [git](https://git-scm.com/) on your computer   
    * [Windows](https://git-scm.com/download/win) Installation
        Note: Keep all settings as default during installation
    * [Mac](https://git-scm.com/download/mac) Installation  
        Note: Mac users can install git using [homebrew](https://brew.sh/) by running `brew install git` in the terminal. You will need to install [homebrew](https://brew.sh/) first if you don't have it   

1. Create a [GitHub](https://github.com/join) Account with your `BYUI-I email`. 
    * Use an [appropriate username](https://workplace.stackexchange.com/questions/83967/does-my-employer-care-about-my-github-username). It will be the name of your public profile and website in Project 6. 
    * If you already have a GitHub account, you can add your BYUI-I email to your existing account. Go to `Settings` -> `Emails` -> `Add email address` and make it your primary email.

1. [Install](https://desktop.github.com/) GitHub Desktop